---
title: "Jobs to be Done"
number-sections: false
---


## Was ist Jobs-to-be-Done?

Jobs-to-be-Done (JTBD) ist ein Konzept, das darauf abzielt, die wahren Gründe hinter den Entscheidungen von Kunden zu verstehen, insbesondere in Bezug auf den Kauf und die Nutzung von Produkten oder Dienstleistungen.

Das Konzept fokussiert sich darauf, den Fortschritt zu verstehen, den Kunden in bestimmten Situationen anstreben, statt nur auf die Aufgaben oder Aktivitäten, die das Produkt unterstützt.

Jobs-to-be-Done bietet daher einen umfassenden Rahmen, um die Bedürfnisse und Motivationen von Kunden zu verstehen und Produkte zu entwickeln, die echten Mehrwert bieten. Es eigent sich als sinnvolle Ergänzung zum Persona-Ansatz, indem der Job in die Beschreibung der Persona integriert wird.

## Soziale, emotionale und funktionale Aspekte

Der Fokus auf den *Kundenfortschritt* im Rahmen von Jobs-to-be-Done bedeutet, alle Aspekte eines Produkts oder einer Dienstleistung zu berücksichtigen, die dazu beitragen, die Lebenssituation des Kunden zu verbessern. Dies umfasst nicht nur funktionale Aspekte, sondern auch soziale und emotionale Elemente.

- **Funktionale Aspekte**: Ein effizientes Haushaltsgerät (z.B. ein intelligenter Staubsauger) erleichtert nicht nur die Reinigung, sondern schafft auch mehr Freizeit für den Benutzer.

- **Emotionale Aspekte**: Ein Musikstreaming-Dienst bietet nicht nur Zugang zu Musik, sondern schafft auch emotionale Erlebnisse, indem er Erinnerungen weckt oder Entspannung fördert.

- **Soziale Aspekte**: Ein Smartphone ermöglicht nicht nur Kommunikation, sondern stärkt auch soziale Bindungen durch gemeinsame Erlebnisse, wie das Teilen von Fotos und Videos.

In der Produktentwicklung ist es wichtig, diese Aspekte zu verstehen und zu berücksichtigen, um Produkte zu schaffen, die einen echten Fortschritt im Leben der Kunden ermöglichen.


## Anwendung des JTBD-Ansatzes

1. **Erforschung der Kundenbedürfnisse**: Tiefgehendes Verständnis des Kunden und seines Kontextes.

2. **Entwicklung und Innovation**: Schaffung von Produkten, die echten Fortschritt für den Kunden ermöglichen.

3. **Fokus auf den Kundenfortschritt**: Berücksichtigung von sozialen, emotionalen und funktionalen Aspekten bei der Produktentwicklung.

Was ist der "Job" eines McDonald's-Milchshakes? Das fragte sich der Harvard Business School-Professor und Experte für disruptive Innovationen Clayton Christensen, als McDonald's an ihn herantrat, um seine Milchshake-Produktlinie zu erneuern. Durch die Aufdeckung der Aufgaben, die ein McDonald's-Milchshake zu erfüllen hat, erkannte das Unternehmen, dass der Markt für Milchshakes siebenmal größer ist, als es gedacht hatte:


<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Stc0beAxavY?si=5Wi0S1W5pJPAStuH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


## Ressourcen

- Die Jobs und Bedürfnisse/Schmerzpunbkte der Kunden können mit Hilfe des Kundensegment-Profils des [Value Proposition Canvas](/docs/value-proposition.qmd) ermittelt werden.

<!--
- Das [Jobs-to-be-Done-Template](https://miro.com/de/templates/jobs-to-be-done/) von Miro kann dabei helfen festzuhalten, wie und warum die Kunden ein Produkt  nutzen und kaufen.
-->