---
title: "User Persona"
number-sections: false
---

## Was ist eine User Persona?

Eine User Persona ist eine fiktive Darstellung eines idealen oder typischen Nutzers eines Produkts, einer Dienstleistung oder einer Website. Sie basiert auf Untersuchungen und Analysen von Nutzerdaten und ermöglicht es Unternehmen und Designern, ihre Zielgruppe besser zu verstehen. 

User Personas enthalten Informationen über Demografie, Motivation, Bedürfnisse, Ziele und Verhalten der Nutzer*innen und liefern wertvolle Erkenntnisse für die Entscheidungsfindung und Produktentwicklung.

Eine [Buyer Persona](docs/buyer-persona.qmd) ist dagegen eine semi-fiktive Darstellung des kaufenden Kunden (welcher nicht zwingend auch Nutzer des Produkts sein muss).

## Bedeutung einer detaillierten User Persona

User Personas sind entscheidend für die Gestaltung und Entwicklung von Produkten und Dienstleistungen. Sie helfen Unternehmen, ein tiefes Verständnis ihrer Zielnutzer/innen zu gewinnen und ihre Angebote auf die spezifischen Bedürfnisse und Vorlieben der Nutzer/innen zuzuschneiden, was das Nutzererlebnis verbessert und zum Erfolg der Produkte oder Dienstleistungen beiträgt.

## Integration des Jobs-to-be-Done-Ansatzes

Der [JTBD-Ansatz](/jobs-to-be-done.qmd) ergänzt User Personas, indem er sich auf die spezifischen Aufgaben konzentriert, die Nutzer/innen erledigen möchten, und bietet tiefere Einblicke in ihre wahren Bedürfnisse und Ziele.

## Erstellung von User Personas mit JTBD

1. **Recherche**: Um genaue Personas zu erstellen, werden Umfragen, Interviews und Datenanalysen genutzt, um demografische Daten, Vorlieben, Verhalten und Motivationen zu sammeln.
2. **Ermittlung der 'Jobs'**: Zusätzlich zu demografischen und psychografischen Daten werden die spezifischen 'Jobs' erfasst, die Nutzer*innen mit dem Produkt oder der Dienstleistung erledigen wollen (dabei sollten funktionale, emotionale und soziale Nutzenkomponenten berücksichtigt werden).
3. **Integration in die Persona-Beschreibung**: Die identifizierten 'Jobs' werden in die Beschreibung der User Persona integriert, um ein umfassenderes Bild der Nutzer*innen zu erstellen.
4. **Fokus auf Lösungen**: Produkte und Dienstleistungen werden so gestaltet, dass sie genau auf die 'Jobs' zugeschnitten sind, die Nutzer*innen erledigen möchten.

## Vorteile von User Personas mit JTBD

Der Einsatz dieser Personas bietet mehrere Vorteile:
- **Verbesserte Entscheidungsfindung**: Unternehmen können fundierte Entscheidungen treffen, die auf den Bedürfnissen und Vorlieben der Nutzer*innen basieren.
- **Effektives Produktdesign und -entwicklung**: Teams verstehen die Bedürfnisse und Probleme der Nutzer*innen besser und können passende Produkte und relevante Funktionen entwickeln.
- **Effektives Marketing und Kommunikation**: Unternehmen können ihre Botschaften und Inhalte auf bestimmte Nutzergruppen zuschneiden.

## Inhalte einer User Persona

Eine umfassende User Persona-Beschreibung enthält in der Regel folgende Elemente (dies ist lediglich ein Vorschlag - Sie können die Inhalte anpassen):

1. **Name und Hintergrund**: 
   - **Name**: Ein fiktiver Name, der die Persona repräsentiert.
   - **Hintergrund**: Eine kurze Geschichte, die den Lebenskontext der Persona beschreibt.
2. **Demografische Daten**: 
   - Alter, Geschlecht, Beruf, Bildungsstand, geografischer Standort.
3. **Psychografische Daten**: 
   - Einstellungen, Interessen, Werte, Lebensgewohnheiten.
4. **Jobs (Jobs-to-be-Done)**: 
   - Die spezifischen Aufgaben oder Probleme, die die Persona mit dem Produkt/Dienstleistung lösen möchte. Welche Ziele sollen erreicht werden (rational, emotional und sozial)?
5. **Bedürfnisse und Schmerzpunkte**: 
   - Welche konkreten Bedürfnisse (rational, emotional und sozial) und Schmerzpunkte hat die Persona? 
6. **Verhaltensweisen und Vorlieben**: 
   - Wie die Persona sich verhält und mit Produkten/Dienstleistungen interagiert.


## Ressourcen

- [Miro User-Persona Template](https://miro.com/templates/personas/) 

## Nächste Schritte

Nachdem die Persona erstellt wurde, können die Bedürfnisse dieser Persona mit  der Wertkarte (Value Map) eines Unternehmens mit Hilfe des [Value Proposition Canvas](/docs/value-proposition.qmd) abgeglichen werden. 